---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openbao
  namespace: vault
spec:
  releaseName: openbao
  chart:
    spec:
      chart: openbao
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: openbao
        namespace: flux-system
      interval: 1m
  interval: 5m
  targetNamespace: vault
