---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 74.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 1m
  interval: 5m
  targetNamespace: monitoring
  values:
    grafana:
      enabled: true
      # grafana.ini:
      #   server:
      #     root_url: "%(protocol)s://%(domain)s/monitoring/grafana"
      #     serve_from_sub_path: true
      # admin:
      #   existingSecret: grafana-admin-credentials
      #   userKey: admin-user
      #   passwordKey: admin-password
