---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: common
  namespace: flux-system
spec:
  interval: 10m
  path: ./src/k8s/common
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: testlab
  namespace: flux-system
spec:
  interval: 10m
  path: ./src/k8s/testlab
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

